package com.svaleroAA2EvRubenLC.dao;

public class TieneDAO {
    /*TODO -- NO SE CREAN CLASES PARA LAS TABLAS EN UNA BASE DE DATOS QUE PROVIENEN DE UNA RELACION N/N.
                ESTAS RELACIONES SE REALIZAN EN JAVA MEDIANTE RELACIONES ENTRE OBJETOS A TRAVES DE LISTAS DE REFERENCIAS A OBJETOS.
     */
}
